blank_issues_enabled: true
contact_links:
  - name: Package chat
    url: https://example.org
    about: Our chat for help and general discussion
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/package
    about: Forum for asking and answering questions about Package
